id: PA9EDEAE8
initial_creation_type: input
source_metadata:
  title: Offering Series
  language: bo
  description: 'Lotsawa House presents the following texts related to the practice
    of offering (mchod pa):'
  volume:
    b558e90833a84bf5b222af2472f8ab65:
      title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
      parent: Eight Auspicious Substances
    9e5f15bdb9c1464ea7d17b68e3b63db3:
      title: Teaching on the Offering of Flowers
      parent: Flower Offering
    2d7f995c5a074501b98825d540566b22:
      title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
        of Offerings of the Sixteen Vajra Goddesses'
      parent: Garland of Offerings
    7269864e818349bdb83ab0440ad4ea8c:
      title: Offering to the Nāgas of Gangtok
      parent: Offering to Nāgas
    c534d5dab7d54a7eadb661a6cc4359ca:
      title: Töpa Gyatsoma Offering Prayer
      parent: Prayers
    52231db6dde443c9ab071dde88653801:
      title: 'The Wish-Granting King of Jewels: An Essential Garland of Offerings'
      parent: Prayers
    5eb12ad2f4b84829a0948afb6dee0b9b:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Prosperity
    0e88b205deca42c1be01a1767e038a9a:
      title: White and Red Sur Offerings That Are Very Easy to Apply
      parent: Sur Offering
    c5f47bf987e94640b803db31f7abc278:
      title: Brief Red Sur Offering
      parent: Sur Offering
    ddba104e34054ab2bb6517236548b8d6:
      title: Brief Sur Offering
      parent: Sur Offering
    e83b9621770543028ebb692b0232599c:
      title: A Means of Offering Sur to the Damsi, Gyalgong and Others
      parent: Sur Offering
    a7e99e11702a4dcc93af1bed792bbed6:
      title: 'Freedom from All Adversity: A Sur Offering to Harmful Influences, Obstacle-Makers
        and Elemental Spirits'
      parent: Sur Offering
    6c7fdf86719f4137b10ae84255460b1d:
      title: The Verse for Offering Water from the Pure Vision, An Ocean of Accomplishments
      parent: Water Offering
created_at: '2022-03-01T05:00:22.324690'
last_modified_at: '2022-03-01T05:00:22.324692'
